version: '3.5'

services:
  redis:
    image: redis:7.0.10-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456
    volumes:
      - redis:/data
  kong:
    build:
      context: ./kong-plugin-internationalization
    volumes:
      - ./kong-plugin-internationalization/kong.yml:/tmp/kong-declarative-config.yml
      - ./kong-plugin-internationalization/kong/plugins/internationalization:/usr/local/lib/luarocks/rocks-5.1/kong-plugin-internationalization/0.1.0-1/lua/kong/plugins/kong-plugin-internationalization
      - ./kong-plugin-internationalization/kong/plugins/internationalization:/usr/local/share/lua/5.1/kong/plugins/kong-plugin-internationalization
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /tmp/kong-declarative-config.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled,kong-plugin-internationalization
    network_mode: host

  translator-engine:
    build:
      context: ./translator
    network_mode: host

  ecommerce-example-api:
    build:
      context: ./ecommerce
    network_mode: host

volumes:
  redis: {}
  kong_data: {}
