version: '3.5'

services:
  redis:
    image: redis:7.0.10-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456
    volumes:
      - redis:/data

volumes:
    redis:
